### PR TITLE
Fix various callback compiler errors

### LINKED ISSUE #12: as_collection has a hidden dependency on value_type
From here:
https://github.com/foonathan/lexy/blob/ccbd79c06715b14ffcf7326518412a4d705daf0c/include/lexy/callback.hpp#L335-L342
This can cause issues with collections that do not define a `value_type` when it does not map sense, such as a [trie](https://github.com/Tessil/hat-trie). An alternative would be to try to optionally detect `value_type`, or just defer to `emplace` since it can accept `value_type` itself, or construct it in place.

Also, this line function can end up invoking `initializer_list` overloads for collections that support them, which can end up as a compiler error:
https://github.com/foonathan/lexy/blob/ccbd79c06715b14ffcf7326518412a4d705daf0c/include/lexy/callback.hpp#L354-L357
An alternative would be to simply construct it as `_sink()`.

### PR DESCRIPTION
**Pull request by Ryan-rsm-McKenzie**
Removes hidden dependencies on `value_type` and ensures types with explicit constructors can be intialized.
Fixes #12

### CODE REVIEW

File: include/lexy/callback.hpp [hunk 1]
```diff
@@ -279,18 +279,16 @@ struct _list
...
-        void operator()(typename T::value_type&& obj)
+        template <typename U>
+        auto operator()(U&& obj) -> decltype(_result.push_back(LEXY_FWD(obj)))
         {
-            _result.push_back(LEXY_MOV(obj));
+            return _result.push_back(LEXY_FWD(obj));
         }
+
         template <typename... Args>
         auto operator()(Args&&... args) -> std::enable_if_t<(sizeof...(Args) > 1)>
```
Comment (foonathan) [inline include/lexy/callback.hpp:293]: I think you can now also remove the enable_if here.

File: include/lexy/callback.hpp [hunk 2]
```diff
@@ -328,18 +327,16 @@ struct _collection
...
-        void operator()(typename T::value_type&& obj)
+        template <typename U>
+        auto operator()(U&& obj) -> decltype(_result.insert(LEXY_FWD(obj)))
         {
-            _result.insert(LEXY_MOV(obj));
+            return _result.insert(LEXY_FWD(obj));
         }
+
         template <typename... Args>
         auto operator()(Args&&... args) -> std::enable_if_t<(sizeof...(Args) > 1)>
```
Comment (foonathan) [inline include/lexy/callback.hpp:341]: ... and here as well.

**Review by foonathan — CHANGES_REQUESTED** [review]
Thank you!

**Review by foonathan — APPROVED** [review]

**Comment by foonathan** [comment]
Thanks again.
